### ISSUE TITLE
Change Title and Add meta tags for SEO 

### ISSUE THREAD

**Issue by Arzzam** [Arzzam/bing-search-bot#11]
1. Add Title as Bing Search Bot
2. Adding meta tags for SEO
3. Add Favicon

Use this logo for Favicon (Ask Permission to access the assets) [Link](https://drive.google.com/drive/folders/182oo5PjgwDAafagoU8xlx5B8MeMFHQgT?usp=sharing)

**Comment by Obikaviola** [comment]
Can I be assigned?

**Comment by Obikaviola** [comment]
Can I be assigned?

**Comment by Arzzam** [comment]
Yeah sure, You can work on this

**Comment by Obikaviola** [comment]
I have sent an email asking for permission to access the logo for the favicon.

**Comment by Arzzam** [comment]
Accepted

**Comment by Arzzam** [comment]
Thanks for your contribution
