### ISSUE TITLE
Looks like a change broke the bot...

### ISSUE THREAD

**Issue by ab17182** [Arzzam/bing-search-bot#18]
There must have been a change somewhere (server or client-side) that is now causing all search results on a PC-based W10/W11 Edge browser to append "FORM=ANNTA1" at the end of the search string.  Points aren't being awarded any longer.   Anyone else experiencing this issue?

![image](https://github.com/Arzzam/bing-search-bot/assets/46659262/049382ab-4771-4089-afb1-dda10053a0a2)

**Comment by Arzzam** [comment]
Yeah, It gets broke, most of the time search doesn't get rewarded so I tries to change that but it gets broke.

Yeah I will fix this

**Comment by Arzzam** [comment]
Please Check now, and inform it

**Comment by ab17182** [comment]
Works great!  Thanks so much!
